In [94]:
import pandas as pd

In [95]:
df = pd.read_csv('resources/powerplants (global) - global_power_plants.csv').sample(n=1000, random_state=0)
# df = pd.read_csv('resources/powerplants (global) - global_power_plants.csv')
df

,country code,country_long,name of powerplant,capacity in MW,latitude,longitude,primary_fuel,secondary fuel,other_fuel2,other_fuel3,start date,owner of plant,generation_gwh_2021,geolocation_source,estimated_generation_gwh_2021
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.0,32.3220,65.1190,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,123.77
1,AFG,Afghanistan,Kandahar DOG,10.0,31.6700,65.7950,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.43
2,AFG,Afghanistan,Kandahar JOL,10.0,31.6230,65.7920,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.64
3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.0,34.5560,69.4787,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,225.06
4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.0,34.6410,69.7170,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,406.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,ZMB,Zambia,Ndola,50.0,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34932,ZMB,Zambia,Nkana,20.0,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34933,ZMB,Zambia,Victoria Falls,108.0,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,575.78
34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.0,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,NaN
34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.0,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,3999.75

In [96]:
df.insert(0, 'id', range(len(df)))
df

,id,country code,country_long,name of powerplant,capacity in MW,latitude,longitude,primary_fuel,secondary fuel,other_fuel2,other_fuel3,start date,owner of plant,generation_gwh_2021,geolocation_source,estimated_generation_gwh_2021
0,0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.0,32.3220,65.1190,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,123.77
1,1,AFG,Afghanistan,Kandahar DOG,10.0,31.6700,65.7950,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.43
2,2,AFG,Afghanistan,Kandahar JOL,10.0,31.6230,65.7920,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.64
3,3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.0,34.5560,69.4787,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,225.06
4,4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.0,34.6410,69.7170,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,406.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,34931,ZMB,Zambia,Ndola,50.0,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34932,34932,ZMB,Zambia,Nkana,20.0,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34933,34933,ZMB,Zambia,Victoria Falls,108.0,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,575.78
34934,34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.0,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,NaN
34935,34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.0,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,3999.75

In [97]:
df.to_csv('resources/processed/PowerPlantDataset.csv', index=False)

In [99]:
new_df = pd.read_csv('resources/processed/PowerPlantDataset.csv')
new_df

,id,country code,country_long,name of powerplant,capacity in MW,latitude,longitude,primary_fuel,secondary fuel,other_fuel2,other_fuel3,start date,owner of plant,generation_gwh_2021,geolocation_source,estimated_generation_gwh_2021
0,0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.0,32.3220,65.1190,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,123.77
1,1,AFG,Afghanistan,Kandahar DOG,10.0,31.6700,65.7950,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.43
2,2,AFG,Afghanistan,Kandahar JOL,10.0,31.6230,65.7920,Solar,NaN,NaN,NaN,NaN,NaN,NaN,Wiki-Solar,18.64
3,3,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.0,34.5560,69.4787,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,225.06
4,4,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.0,34.6410,69.7170,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,406.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34931,34931,ZMB,Zambia,Ndola,50.0,-12.9667,28.6333,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34932,34932,ZMB,Zambia,Nkana,20.0,-12.8167,28.2000,Oil,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,NaN
34933,34933,ZMB,Zambia,Victoria Falls,108.0,-17.9167,25.8500,Hydro,NaN,NaN,NaN,NaN,ZESCO,NaN,Power Africa,575.78
34934,34934,ZWE,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.0,-18.3835,26.4700,Coal,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,NaN
34935,34935,ZWE,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.0,-16.5222,28.7619,Hydro,NaN,NaN,NaN,NaN,NaN,NaN,GEODB,3999.75

In [ ]:
country_df = pd.read_csv('resources/world-data-2023.csv')
country_df

In [ ]:
country_df['GDP'] = country_df['GDP'].str.strip('$')

# Turn GDP and Population into numerical values

In [ ]:
country_df['GDP'] = country_df['GDP'].str.replace(',', '').astype(float)
country_df = country_df.loc[:][country_df['Population'].notna()]
country_df['Population'] = country_df['Population'].str.replace(',', '').astype(int)

In [ ]:
country_df

In [ ]:
country_df.to_csv('resources/processed/CountryData.csv', index=False)